# -*- coding: utf-8 -*-
"""creditCard.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w1nKORJkhaXDK2h-Lb5Ojbu_N5jSQb0G
"""

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

credited_card_df = pd.read_csv('/content/drive/MyDrive/dataset/creditcard.csv')
credited_card_df.head()

credited_card_df.info()

credited_card_df.shape

credited_card_df['Class'].value_counts()

credited_card_df.describe() # stastic tell here

legit = credited_card_df[credited_card_df.Class==0]
fraud = credited_card_df[credited_card_df.Class==1]

legit.value_counts()

legit.shape

fraud.shape

legit_sample = legit.sample(n=492) # Use legit.sample instead of legit_sample()
credited_card_df = pd.concat([legit_sample,fraud],axis=0)

credited_card_df['Class'].value_counts()

credited_card_df.groupby('Class').mean()

x = credited_card_df.drop('Class',axis=1)
y = credited_card_df['Class']

x.shape

y.shape

X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, stratify=y, random_state=2)

# train logistic regression model
model = LogisticRegression()
model.fit(X_train, y_train)
ypred = model.predict(X_test)

accuracy_score(ypred, y_test)