# -*- coding: utf-8 -*-
"""Customer_Segmentation(Kmean).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Txt5e7HDxQ10x1uy-bQjQCTTN1jwuscx
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.cluster import KMeans

customer_data = pd.read_csv("/content/drive/MyDrive/dataset/Mall_Customers.csv")

customer_data.head()

customer_data.shape

customer_data.info()

customer_data.isnull().sum()

X= customer_data.iloc[:,[3,4]].values

print(X)

wcss = []

for i in range(1,11):
  kmeans = KMeans(n_clusters=i, init = 'k-means++',random_state=42)
  kmeans.fit(X)
  wcss.append(kmeans.inertia_)



sns.set()
plt.plot(range(1,11),wcss)
plt.title('The Elbow Point Graph')
plt.xlabel('Number of Clusters')
plt.ylabel('WCSS')
plt.show()

kmeans = KMeans(n_clusters=5, init='k-means++', random_state=0)
Y = kmeans.fit_predict(X)

print(Y)

plt.figure(figsize=(8, 6))  # Adjust figure size for better visualization
plt.scatter(X[Y==0,0], X[Y==0,1], s=50, c='green', label='Cluster 1')
plt.scatter(X[Y==1,0], X[Y==1,1], s=50, c='blue', label='Cluster 2')
plt.scatter(X[Y==2,0], X[Y==2,1], s=50, c='red', label='Cluster 3')
plt.scatter(X[Y==3,0], X[Y==3,1], s=50, c='pink', label='Cluster 4')
plt.scatter(X[Y==4,0], X[Y==4,1], s=50, c='yellow', label='Cluster 5')

# Correct the slicing to plot centroids
plt.scatter(kmeans.cluster_centers_[:, 0], kmeans.cluster_centers_[:, 1], s=100, c='cyan', label='Centroids')
# kmeans.cluster_centers_[:, 0] selects all rows (:) and the first column (0) for x-coordinates
# kmeans.cluster_centers_[:, 1] selects all rows (:) and the second column (1) for y-coordinates


plt.title('Customer Groups')
plt.xlabel('Annual Income')
plt.ylabel('Spending Score')
plt.show()

